language: node_js

before_install:
 - sudo apt-get install libgmp3-dev
 - npm install --upgrade npm -g

node_js:
 - "0.10"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false
