language: node_js

before_install:
 - sudo apt-get install libgmp3-dev
 - npm install --upgrade npm -g

node_js:
 - "0.8"
 - "0.10"

notifications:
  email:
    - lloyd@mozilla.com
    - benadida@mozilla.com
    - warner@mozilla.com
